/**
 * exercises.js — Exercise catalog for the Week Builder's block-detail modal
 *
 * Plain config, same pattern as templates.js/foods.js: editable content, not
 * user data. Each training-block *template* (templates.js) represents a whole
 * session type (e.g. "Sweet Spot Ride"); this catalog is one level more
 * granular — the actual exercises/drills a person can draw from when a block
 * of a given category lands on their week. Grouped by the same 8 categories
 * as BLOCK_CATEGORY_STYLE (blockStyleConfig.js) so the modal can filter by
 * `block.blockType` directly with no mapping table needed.
 *
 * `insight` is a separate field from `description` — description says WHAT
 * the exercise is, insight is a coaching cue/pitfall for the "Exercise
 * Insights" panel (weekBuilder.js), deeper than the compact swap-list card.
 *
 * `mode` + `timer` — added so the Sprint Timer (and the Week Builder's
 * inline timer widget, see workoutQueue.js) can run a workout directly
 * instead of trying to parse `dosage` free text:
 *   - 'interval': discrete work/rest rounds. `timer: { rounds, workSec, restSec }`.
 *   - 'steady':   one continuous effort, no rounds/rest. `timer: { durationSec }`.
 *   - 'strength': sets x reps, tracked manually, not by a countdown. `timer: null`.
 *   - 'mobility': holds/flows, same as strength — no countdown. `timer: null`.
 * The distinction is structural (continuous vs. repeated-with-rest), not
 * intensity — a hard continuous Tempo Run is still 'steady', a gentle
 * Strides drill is still 'interval'. This is what fixes the bug where an
 * easy/steady run incorrectly opened the same rounds-based timer UI as a
 * real interval session: routing now keys off this field, not the sport.
 */

const EXERCISE_TEMPLATES = [
  // ── Running ────────────────────────────────────────────────────────────
  { id: 'run_zone2_easy',        category: 'run', name: 'Zone 2 Easy Run',              description: 'Conversational-pace aerobic run — the base-building bulk of any running plan.', dosage: '30-60 min', equipment: 'None', difficulty: 'beginner', insight: 'Should feel easy enough to hold a full conversation the whole time.', mode: 'steady', timer: { durationSec: 2700 } },
  { id: 'run_tempo',              category: 'run', name: 'Tempo Run',                    description: 'Sustained "comfortably hard" effort just below lactate threshold.', dosage: '20-30 min continuous', equipment: 'None', difficulty: 'intermediate', insight: 'Effort should feel comfortably hard and sustainable, not a race.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'run_interval_400',       category: 'run', name: '400m Intervals',               description: 'Short, fast repeats to build speed and running economy.', dosage: '8-12 x 400m, 90s jog rest', equipment: 'Track', difficulty: 'intermediate', insight: 'Aim for consistent lap splits, not a fast first rep that fades.', mode: 'interval', timer: { rounds: 10, workSec: 100, restSec: 90 } },
  { id: 'run_interval_800',       category: 'run', name: '800m Intervals',               description: 'Mid-distance repeats targeting VO2max.', dosage: '5-6 x 800m, 2min jog rest', equipment: 'Track', difficulty: 'advanced', insight: 'Even pacing across every repeat beats one fast rep and a fade.', mode: 'interval', timer: { rounds: 6, workSec: 200, restSec: 120 } },
  { id: 'run_hill_repeats',       category: 'run', name: 'Hill Repeats',                 description: 'Uphill efforts building strength and power with low impact.', dosage: '6-10 x 60s uphill, jog down recovery', equipment: 'Hill', difficulty: 'intermediate', insight: 'Drive with the arms and keep the stride short and quick uphill.', mode: 'interval', timer: { rounds: 8, workSec: 60, restSec: 90 } },
  { id: 'run_fartlek',            category: 'run', name: 'Fartlek Run',                  description: 'Unstructured speed play — alternating fast and easy segments by feel.', dosage: '30-40 min with 6-8 surges', equipment: 'None', difficulty: 'beginner', insight: 'Let effort be driven by feel, not a stopwatch or fixed distance.', mode: 'steady', timer: { durationSec: 2100 } },
  { id: 'run_lsd',                category: 'run', name: 'Long Slow Distance',           description: 'The weekly long run — builds endurance and fat-burning capacity.', dosage: '60-120 min easy', equipment: 'None', difficulty: 'beginner', insight: 'Resist speeding up — time at an easy effort is the entire point.', mode: 'steady', timer: { durationSec: 5400 } },
  { id: 'run_progression',        category: 'run', name: 'Progression Run',              description: 'Starts easy and gradually speeds up each mile/km.', dosage: '40-50 min, negative split', equipment: 'None', difficulty: 'intermediate', insight: 'Start slower than feels necessary so the finish has room to build.', mode: 'steady', timer: { durationSec: 2700 } },
  { id: 'run_recovery_jog',       category: 'run', name: 'Recovery Jog',                 description: 'Very easy shakeout run to promote blood flow after a hard session.', dosage: '15-25 min, very easy', equipment: 'None', difficulty: 'beginner', insight: "If it doesn't feel almost too slow, it's too fast for a recovery day.", mode: 'steady', timer: { durationSec: 1200 } },
  { id: 'run_strides',            category: 'run', name: 'Strides (100m Accelerations)', description: 'Short controlled accelerations to sharpen leg speed and form.', dosage: '6-8 x 100m, full recovery', equipment: 'None', difficulty: 'beginner', insight: 'Full recovery between reps — this builds speed and form, not fitness.', mode: 'interval', timer: { rounds: 7, workSec: 20, restSec: 90 } },
  { id: 'run_1600_repeats',       category: 'run', name: '1600m Track Repeats',          description: 'Full-lap repeats at 5K-10K race pace for aerobic power.', dosage: '4-5 x 1600m, 3min rest', equipment: 'Track', difficulty: 'advanced', insight: 'Even splits at goal pace beat a fast first lap and a fade.', mode: 'interval', timer: { rounds: 5, workSec: 420, restSec: 180 } },
  { id: 'run_negative_split',     category: 'run', name: 'Negative Split Run',            description: 'Deliberately run the second half faster than the first.', dosage: '45-60 min', equipment: 'None', difficulty: 'intermediate', insight: 'Bank patience early — the second half should feel earned, not desperate.', mode: 'steady', timer: { durationSec: 3150 } },
  { id: 'run_treadmill_incline',  category: 'run', name: 'Treadmill Incline Walk-Run',    description: 'Alternating incline walking and running for low-impact aerobic load.', dosage: '30-40 min, 4-10% incline', equipment: 'Treadmill', difficulty: 'beginner', insight: 'A solid low-impact substitute for hill repeats when trails aren\'t available.', mode: 'steady', timer: { durationSec: 2100 } },
  { id: 'run_marathon_pace',      category: 'run', name: 'Marathon Pace Run',            description: 'Extended effort locked at target marathon race pace.', dosage: '40-90 min at goal pace', equipment: 'None', difficulty: 'advanced', insight: 'Practicing fueling and hydration here matters as much as the pace.', mode: 'steady', timer: { durationSec: 3900 } },
  { id: 'run_5k_time_trial',      category: 'run', name: '5K Time Trial',                description: 'All-out 5K effort to test current fitness.', dosage: '1 x 5K, max effort', equipment: 'None', difficulty: 'advanced', insight: 'Warm up thoroughly — this effort starts hard from the first minute.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'run_10k_time_trial',     category: 'run', name: '10K Time Trial',               description: 'All-out 10K effort to test current fitness.', dosage: '1 x 10K, max effort', equipment: 'None', difficulty: 'advanced', insight: 'Pacing discipline in the first 2K prevents a blow-up in the last 2K.', mode: 'steady', timer: { durationSec: 3000 } },
  { id: 'run_yasso_800s',         category: 'run', name: 'Yasso 800s',                   description: 'Classic marathon-predictor set — 800m repeats at target marathon-minute pace.', dosage: '6-10 x 800m, equal-time jog rest', equipment: 'Track', difficulty: 'advanced', insight: 'Your average 800m split in minutes:seconds roughly predicts marathon time in hours:minutes.', mode: 'interval', timer: { rounds: 8, workSec: 200, restSec: 200 } },
  { id: 'run_fartlek_pyramid',    category: 'run', name: 'Fartlek Pyramid',              description: 'Structured surges that build up then back down in duration (1-2-3-2-1 min).', dosage: '~30 min total', equipment: 'None', difficulty: 'intermediate', insight: 'The longest middle surge is the hardest — pace it, don\'t sprint it.', mode: 'steady', timer: { durationSec: 1800 } },
  { id: 'run_cadence_drill',      category: 'run', name: 'Cadence Drill Run',            description: 'Easy run focused on increasing steps-per-minute for efficiency.', dosage: '20-30 min @ 170-180 spm', equipment: 'Metronome app', difficulty: 'beginner', insight: 'Shorter, quicker steps reduce impact more reliably than chasing a specific number.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'run_minimalist_strides', category: 'run', name: 'Barefoot/Minimalist Strides',  description: 'Short barefoot or minimalist-shoe strides on grass to build foot strength.', dosage: '4-6 x 50m', equipment: 'None', difficulty: 'intermediate', insight: 'Start on soft grass — foot strength builds gradually, not overnight.', mode: 'interval', timer: { rounds: 5, workSec: 15, restSec: 60 } },
  { id: 'run_downhill_repeats',   category: 'run', name: 'Downhill Repeats',             description: 'Controlled fast descents to train leg turnover and eccentric strength.', dosage: '6-8 x 30s downhill', equipment: 'Hill', difficulty: 'intermediate', insight: 'Let gravity do the work — overstriding downhill is what causes soreness.', mode: 'interval', timer: { rounds: 7, workSec: 30, restSec: 60 } },
  { id: 'run_uphill_sprints',     category: 'run', name: 'Uphill Sprint Repeats',        description: 'Short maximal-effort uphill sprints for power without joint impact.', dosage: '8-10 x 10-15s, full recovery', equipment: 'Hill', difficulty: 'advanced', insight: 'Full recovery is essential here — this trains power, not conditioning.', mode: 'interval', timer: { rounds: 9, workSec: 12, restSec: 120 } },
  { id: 'run_brick',               category: 'run', name: 'Brick Run (Post-Bike)',        description: 'Short run immediately after cycling to train the run-off-the-bike feel.', dosage: '15-20 min off the bike', equipment: 'None', difficulty: 'intermediate', insight: 'Heavy, awkward legs for the first few minutes is normal, not a bad sign.', mode: 'steady', timer: { durationSec: 1050 } },
  { id: 'run_treadmill_speed',    category: 'run', name: 'Treadmill Speed Intervals',    description: 'Controlled-pace speed intervals using the treadmill\'s fixed belt speed.', dosage: '6 x 2min @ 5K pace, 90s easy', equipment: 'Treadmill', difficulty: 'intermediate', insight: 'The belt sets the pace for you — use it to lock in goal splits precisely.', mode: 'interval', timer: { rounds: 6, workSec: 120, restSec: 90 } },
  { id: 'run_shakeout',            category: 'run', name: 'Easy Shakeout Run',           description: 'Very short, very easy pre-race day run to stay loose.', dosage: '10-15 min easy', equipment: 'None', difficulty: 'beginner', insight: 'Purpose is to feel loose, not to add fitness — keep it short.', mode: 'steady', timer: { durationSec: 720 } },

  // ── Trail Running ──────────────────────────────────────────────────────
  { id: 'trail_technical_singletrack', category: 'trail', name: 'Technical Singletrack Run', description: 'Running narrow, twisting trail focused on foot placement and quick reactions.', dosage: '30-60 min', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Look ahead, not down at your feet — the trail rewards anticipation.', mode: 'steady', timer: { durationSec: 2700 } },
  { id: 'trail_vert_hike_run',    category: 'trail', name: 'Vertical Gain Hike-Run',      description: 'Alternating hiking and running to accumulate elevation gain efficiently.', dosage: '45-90 min, 300m+ vert', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Hike the steepest sections — running them rarely saves meaningful time.', mode: 'steady', timer: { durationSec: 4050 } },
  { id: 'trail_downhill_technique', category: 'trail', name: 'Downhill Technique Drill',  description: 'Deliberate practice of quick feet and forward lean on technical descents.', dosage: '20-30 min of repeated descents', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Quick, light steps beat long braking strides on technical descents.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'trail_power_hiking',     category: 'trail', name: 'Power Hiking Intervals',      description: 'Hands-on-knees hiking intervals for steep, unrunnable grades.', dosage: '8-10 x 3min steep hike', equipment: 'Poles (optional)', difficulty: 'beginner', insight: 'Hands on the knees or quads add real leverage on the steepest pitches.', mode: 'interval', timer: { rounds: 9, workSec: 180, restSec: 90 } },
  { id: 'trail_fartlek',          category: 'trail', name: 'Trail Fartlek',               description: 'Unstructured speed play adapted to whatever terrain presents itself.', dosage: '40-50 min', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Let terrain dictate the surges — a short climb is a natural interval.', mode: 'steady', timer: { durationSec: 2700 } },
  { id: 'trail_agility_run',      category: 'trail', name: 'Rock/Root Agility Run',       description: 'Slow, deliberate running over technical rock/root sections to build footing confidence.', dosage: '20-30 min', equipment: 'Trail shoes', difficulty: 'beginner', insight: 'Slow down enough to place each foot deliberately — speed comes later.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'trail_long_tof',         category: 'trail', name: 'Long Trail Run (Time on Feet)', description: 'Ultra-style long effort measured by duration, not pace.', dosage: '2-5 hours', equipment: 'Hydration pack', difficulty: 'advanced', insight: 'Fuel and hydrate on a schedule, not just when you notice you\'re thirsty.', mode: 'steady', timer: { durationSec: 12600 } },
  { id: 'trail_scree_descent',    category: 'trail', name: 'Scree/Loose Ground Descent Practice', description: 'Controlled skiing-style descent technique on loose, unstable footing.', dosage: '15-20 min', equipment: 'Trail shoes', difficulty: 'advanced', insight: 'Small, quick steps with a slight backward lean control speed better than big strides.', mode: 'steady', timer: { durationSec: 1050 } },
  { id: 'trail_short_loop_repeats', category: 'trail', name: 'Trail Repeats (Short Loop)', description: 'Repeated short technical loop to drill terrain-specific fitness.', dosage: '4-6 laps of a 1-2km loop', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Repetition on one loop builds real technical skill, not just fitness.', mode: 'interval', timer: { rounds: 5, workSec: 420, restSec: 60 } },
  { id: 'trail_ridge_run',        category: 'trail', name: 'Ridge Run',                    description: 'Exposed high-ridge running combining endurance with careful footing and pacing.', dosage: '60-120 min', equipment: 'Trail shoes', difficulty: 'advanced', insight: 'Check weather and wind exposure first — ridgelines offer no shelter.', mode: 'steady', timer: { durationSec: 5400 } },
  { id: 'trail_river_crossing',   category: 'trail', name: 'River Crossing Practice',      description: 'Technique and confidence-building for wading/crossing moving water safely.', dosage: '3-5 crossings', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Unclip pack hip belts before crossing moving water.', mode: 'interval', timer: { rounds: 4, workSec: 60, restSec: 60 } },
  { id: 'trail_night_run',        category: 'trail', name: 'Night Trail Run (Headlamp)',   description: 'Trail running in low light to build night-navigation skills for ultras.', dosage: '45-60 min', equipment: 'Headlamp', difficulty: 'advanced', insight: 'A dimmer, wider beam often helps depth perception more than raw brightness.', mode: 'steady', timer: { durationSec: 3150 } },
  { id: 'trail_backyard_loop',    category: 'trail', name: 'Backyard Ultra Loop Simulation', description: 'Repeated fixed-distance loop at an even pace, simulating backyard-ultra format.', dosage: '4-8 x 6.7km loop, on the hour', equipment: 'Trail shoes', difficulty: 'advanced', insight: 'The real skill is discipline — resist starting each lap too fast.', mode: 'interval', timer: { rounds: 6, workSec: 3300, restSec: 300 } },
  { id: 'trail_steep_power_hike', category: 'trail', name: 'Steep Grade Power Hike',       description: 'Sustained steep hiking for pure vertical-gain conditioning.', dosage: '30-45 min continuous', equipment: 'Poles (optional)', difficulty: 'intermediate', insight: 'A steady, sustainable rhythm beats stop-and-start bursts on long climbs.', mode: 'steady', timer: { durationSec: 2250 } },
  { id: 'trail_sprint_finish',    category: 'trail', name: 'Trail Sprint Finish Practice', description: 'Practicing a hard finishing kick on tired legs at the end of a long effort.', dosage: '3-4 x 60s at the end of a run', equipment: 'Trail shoes', difficulty: 'advanced', insight: 'Practice this on already-tired legs specifically — that\'s the real race scenario.', mode: 'interval', timer: { rounds: 3, workSec: 60, restSec: 90 } },
  { id: 'trail_switchback_drill', category: 'trail', name: 'Switchback Descent Drill',    description: 'Repeated tight-switchback descents to train cornering and edge control.', dosage: '8-10 switchbacks, repeated', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Only cut the inside line when footing is secure — control beats speed.', mode: 'interval', timer: { rounds: 9, workSec: 30, restSec: 45 } },
  { id: 'trail_mud_run',          category: 'trail', name: 'Mud/Wet Terrain Run',          description: 'Running in slick conditions to build balance and confidence in bad weather.', dosage: '30-45 min', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'A shorter stride and mid-foot strike reduce slipping on slick ground.', mode: 'steady', timer: { durationSec: 2250 } },
  { id: 'trail_altitude_hike',    category: 'trail', name: 'Altitude Acclimation Hike',    description: 'Easy-paced hiking at elevation to support acclimatization.', dosage: '60-90 min easy', equipment: 'None', difficulty: 'beginner', insight: 'Keep effort easy — altitude adaptation takes days, not one hard session.', mode: 'steady', timer: { durationSec: 4500 } },
  { id: 'trail_scramble_climb',   category: 'trail', name: 'Technical Climb Scramble',     description: 'Hands-and-feet scrambling practice for exposed, rocky ascents.', dosage: '20-30 min', equipment: 'None', difficulty: 'advanced', insight: 'Keep three points of contact at all times on exposed scrambles.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'trail_recovery_jog',     category: 'trail', name: 'Trail Recovery Jog',           description: 'Very easy trail jog on soft, forgiving terrain the day after a long effort.', dosage: '20-30 min easy', equipment: 'Trail shoes', difficulty: 'beginner', insight: 'Pick the softest, flattest terrain available — save technical trail for another day.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'trail_weighted_hike',    category: 'trail', name: 'Pack-Weighted Trail Hike',     description: 'Hiking with a loaded pack to build strength for multi-day or aid-station carries.', dosage: '60-90 min, 5-8kg pack', equipment: 'Weighted pack', difficulty: 'intermediate', insight: 'Add pack weight gradually — sudden heavy loads are a common injury cause.', mode: 'steady', timer: { durationSec: 4500 } },
  { id: 'trail_quad_downhill',    category: 'trail', name: 'Downhill Quad Strength Run',   description: 'Repeated moderate descents specifically to build eccentric quad durability.', dosage: '5-6 x 2min downhill', equipment: 'Trail shoes', difficulty: 'advanced', insight: 'Some next-day soreness here is expected — that\'s the eccentric adaptation working.', mode: 'interval', timer: { rounds: 6, workSec: 120, restSec: 120 } },
  { id: 'trail_cornering_drill',  category: 'trail', name: 'Singletrack Cornering Drill', description: 'Deliberate practice cutting corners efficiently on flowing singletrack.', dosage: '15-20 min of repeated corners', equipment: 'Trail shoes', difficulty: 'intermediate', insight: 'Lean slightly into the turn and look through the corner, not at your feet.', mode: 'steady', timer: { durationSec: 1050 } },
  { id: 'trail_multi_terrain',    category: 'trail', name: 'Multi-Terrain Long Run',       description: 'Long run mixing road, gravel, and singletrack to build varied-surface resilience.', dosage: '90-150 min', equipment: 'Trail shoes', difficulty: 'advanced', insight: 'Expect pace to vary a lot — effort, not speed, is the target here.', mode: 'steady', timer: { durationSec: 7200 } },
  { id: 'trail_sunrise_run',      category: 'trail', name: 'Sunrise/Sunset Trail Run',     description: 'Easy-paced scenic run — as much a mental-recovery session as a physical one.', dosage: '30-60 min easy', equipment: 'Headlamp (optional)', difficulty: 'beginner', insight: 'No pace goals needed — this run is about mental reset as much as fitness.', mode: 'steady', timer: { durationSec: 2700 } },

  // ── Weight Training ────────────────────────────────────────────────────
  { id: 'weights_back_squat',     category: 'weights', name: 'Barbell Back Squat',        description: 'Foundational compound lower-body lift for strength and mass.', dosage: '4 x 6-8', equipment: 'Barbell, rack', difficulty: 'intermediate', insight: 'Brace the core and keep the chest up through the entire rep.', mode: 'strength', timer: null },
  { id: 'weights_front_squat',    category: 'weights', name: 'Barbell Front Squat',        description: 'Quad- and core-dominant squat variation with an anterior load.', dosage: '4 x 5-8', equipment: 'Barbell, rack', difficulty: 'advanced', insight: 'Elbows high — a dropping front rack usually means the bar is too heavy.', mode: 'strength', timer: null },
  { id: 'weights_deadlift',       category: 'weights', name: 'Conventional Deadlift',       description: 'The benchmark full-body pulling lift for posterior-chain strength.', dosage: '4 x 5', equipment: 'Barbell', difficulty: 'intermediate', insight: 'Push the floor away with your legs rather than pulling with your back.', mode: 'strength', timer: null },
  { id: 'weights_rdl',            category: 'weights', name: 'Romanian Deadlift',           description: 'Hip-hinge variation targeting hamstrings and glutes with a fixed knee bend.', dosage: '3 x 8-10', equipment: 'Barbell', difficulty: 'intermediate', insight: 'The hips drive the movement — knees stay softly bent, never locked.', mode: 'strength', timer: null },
  { id: 'weights_bench_press',    category: 'weights', name: 'Bench Press',                description: 'Primary horizontal pressing lift for chest, shoulders, and triceps.', dosage: '4 x 6-8', equipment: 'Barbell, bench', difficulty: 'intermediate', insight: 'Keep shoulder blades pinched back for a stable, safer pressing base.', mode: 'strength', timer: null },
  { id: 'weights_overhead_press', category: 'weights', name: 'Overhead Press',             description: 'Standing vertical press building shoulder strength and core stability.', dosage: '4 x 6-8', equipment: 'Barbell', difficulty: 'intermediate', insight: 'Squeeze the glutes to avoid overarching the lower back as the bar passes your face.', mode: 'strength', timer: null },
  { id: 'weights_barbell_row',    category: 'weights', name: 'Barbell Row',                description: 'Bent-over horizontal pull for upper-back thickness and strength.', dosage: '4 x 8-10', equipment: 'Barbell', difficulty: 'intermediate', insight: 'Pull to the lower ribs, not the neck, to keep tension on the back.', mode: 'strength', timer: null },
  { id: 'weights_weighted_pullup', category: 'weights', name: 'Weighted Pull-Up',          description: 'Pull-up with added external load once bodyweight reps are easy.', dosage: '4 x 4-6', equipment: 'Pull-up bar, weight belt', difficulty: 'advanced', insight: 'Add load only once strict bodyweight reps are clean and fully controlled.', mode: 'strength', timer: null },
  { id: 'weights_bulgarian_split', category: 'weights', name: 'Bulgarian Split Squat',      description: 'Rear-foot-elevated single-leg squat for unilateral strength and balance.', dosage: '3 x 8-10 per leg', equipment: 'Bench, dumbbells', difficulty: 'intermediate', insight: 'Most of the work should be felt in the front leg, not the rear one.', mode: 'strength', timer: null },
  { id: 'weights_walking_lunge',  category: 'weights', name: 'Walking Lunge',              description: 'Dynamic single-leg movement building strength through a long range of motion.', dosage: '3 x 10-12 per leg', equipment: 'Dumbbells', difficulty: 'beginner', insight: 'Step long enough that the front knee tracks over the ankle, not past it.', mode: 'strength', timer: null },
  { id: 'weights_hip_thrust',     category: 'weights', name: 'Hip Thrust',                 description: 'Glute-isolation hip extension movement, high loading potential.', dosage: '3 x 10-12', equipment: 'Barbell, bench', difficulty: 'beginner', insight: 'Tuck the chin and squeeze the glutes hard at the top — don\'t just lift the hips.', mode: 'strength', timer: null },
  { id: 'weights_leg_press',      category: 'weights', name: 'Leg Press',                  description: 'Machine-based compound leg movement with a fixed, joint-friendly path.', dosage: '3 x 10-12', equipment: 'Leg press machine', difficulty: 'beginner', insight: "Don't let the lower back round off the pad at the bottom of the rep.", mode: 'strength', timer: null },
  { id: 'weights_db_bench',       category: 'weights', name: 'Dumbbell Bench Press',        description: 'Bench press variation allowing a deeper range of motion and unilateral loading.', dosage: '3 x 8-10', equipment: 'Dumbbells, bench', difficulty: 'beginner', insight: 'The extra range of motion versus a barbell is the whole point — use it fully.', mode: 'strength', timer: null },
  { id: 'weights_incline_db_press', category: 'weights', name: 'Incline Dumbbell Press',    description: 'Upper-chest-focused pressing on an inclined bench.', dosage: '3 x 8-10', equipment: 'Dumbbells, bench', difficulty: 'beginner', insight: 'A steep incline shifts work toward the shoulders — a moderate angle keeps it chest-focused.', mode: 'strength', timer: null },
  { id: 'weights_seated_cable_row', category: 'weights', name: 'Seated Cable Row',          description: 'Machine row building mid-back thickness with constant cable tension.', dosage: '3 x 10-12', equipment: 'Cable machine', difficulty: 'beginner', insight: 'Keep the torso still — rowing with momentum trades back work for lower-back strain.', mode: 'strength', timer: null },
  { id: 'weights_lat_pulldown',   category: 'weights', name: 'Lat Pulldown',                description: 'Vertical pulling movement and an accessible pull-up regression.', dosage: '3 x 10-12', equipment: 'Cable machine', difficulty: 'beginner', insight: 'Pull with the elbows, not the hands, to actually feel the lats working.', mode: 'strength', timer: null },
  { id: 'weights_db_shoulder_press', category: 'weights', name: 'Dumbbell Shoulder Press',   description: 'Seated or standing overhead press using dumbbells for a fuller range of motion.', dosage: '3 x 8-10', equipment: 'Dumbbells', difficulty: 'beginner', insight: 'A neutral, palms-in grip is often more shoulder-friendly than palms-forward.', mode: 'strength', timer: null },
  { id: 'weights_barbell_hip_thrust', category: 'weights', name: 'Barbell Hip Thrust',       description: 'Heavier-loaded hip thrust variation for maximal glute strength.', dosage: '4 x 6-8', equipment: 'Barbell, bench, pad', difficulty: 'intermediate', insight: 'Pad the bar well — this is a genuinely heavy-loading movement once progressed.', mode: 'strength', timer: null },
  { id: 'weights_trap_bar_deadlift', category: 'weights', name: 'Trap Bar Deadlift',         description: 'More upright, joint-friendly deadlift variant using a hex/trap bar.', dosage: '4 x 6-8', equipment: 'Trap bar', difficulty: 'beginner', insight: 'The more upright torso angle is easier on the lower back than a conventional pull.', mode: 'strength', timer: null },
  { id: 'weights_goblet_squat',   category: 'weights', name: 'Goblet Squat',                description: 'Front-loaded squat variation that reinforces upright torso position — a great beginner squat pattern.', dosage: '3 x 10-12', equipment: 'Kettlebell/dumbbell', difficulty: 'beginner', insight: 'Holding the weight in front naturally teaches an upright, safe squat pattern.', mode: 'strength', timer: null },
  { id: 'weights_db_row',         category: 'weights', name: 'Single-Arm Dumbbell Row',      description: 'Unilateral row that also challenges anti-rotation core stability.', dosage: '3 x 10-12 per side', equipment: 'Dumbbell, bench', difficulty: 'beginner', insight: 'Resist rotating the torso toward the working arm — that\'s momentum, not back strength.', mode: 'strength', timer: null },
  { id: 'weights_face_pull',      category: 'weights', name: 'Face Pull',                   description: 'Rear-delt and rotator-cuff accessory movement for shoulder health.', dosage: '3 x 15-20', equipment: 'Cable machine, rope attachment', difficulty: 'beginner', insight: 'Pull to eye level with high elbows — this is a posture-correcting move.', mode: 'strength', timer: null },
  { id: 'weights_barbell_curl',   category: 'weights', name: 'Barbell Curl',                description: 'Classic isolation movement for biceps strength and size.', dosage: '3 x 10-12', equipment: 'Barbell/EZ-bar', difficulty: 'beginner', insight: 'Keep elbows pinned at your sides — swinging them forward reduces bicep work.', mode: 'strength', timer: null },
  { id: 'weights_skull_crusher',  category: 'weights', name: 'Skull Crusher (Triceps Extension)', description: 'Lying triceps isolation movement.', dosage: '3 x 10-12', equipment: 'EZ-bar/dumbbells, bench', difficulty: 'intermediate', insight: 'Elbows stay fixed in place — only the forearm should move.', mode: 'strength', timer: null },
  { id: 'weights_farmers_carry',  category: 'weights', name: "Farmer's Carry",              description: 'Loaded carry building grip, core, and total-body strength endurance.', dosage: '3 x 30-40m', equipment: 'Dumbbells/kettlebells', difficulty: 'beginner', insight: 'Walk tall — this is as much a core and grip exercise as a leg one.', mode: 'strength', timer: null },

  // ── Calisthenics ───────────────────────────────────────────────────────
  { id: 'cal_pushup',             category: 'calisthenics', name: 'Push-Up',                description: 'Foundational horizontal press building chest, shoulder, and triceps strength.', dosage: '3 x 10-15', equipment: 'None', difficulty: 'beginner', insight: 'Keep a straight line from head to heels — sagging hips is the most common flaw.', mode: 'strength', timer: null },
  { id: 'cal_pike_pushup',        category: 'calisthenics', name: 'Pike Push-Up',           description: 'Shoulder-dominant push-up regression on the path to a handstand push-up.', dosage: '3 x 8-12', equipment: 'None', difficulty: 'intermediate', insight: 'The steeper the hip angle, the more shoulder-dominant — and harder — it becomes.', mode: 'strength', timer: null },
  { id: 'cal_wall_hspu',          category: 'calisthenics', name: 'Handstand Push-Up (Wall)', description: 'Vertical pressing strength using the wall for balance support.', dosage: '3 x 3-6', equipment: 'Wall', difficulty: 'advanced', insight: 'Master a solid wall handstand hold before adding the pressing movement.', mode: 'strength', timer: null },
  { id: 'cal_dip',                category: 'calisthenics', name: 'Dip (Parallel Bars)',     description: 'Deep-range pressing movement for chest, shoulders, and triceps.', dosage: '3 x 8-12', equipment: 'Parallel bars/rings', difficulty: 'intermediate', insight: 'A slight forward lean shifts work to the chest; staying upright favors triceps.', mode: 'strength', timer: null },
  { id: 'cal_pullup',             category: 'calisthenics', name: 'Pull-Up',                description: 'The benchmark vertical pulling movement for back and biceps strength.', dosage: '3 x 5-10', equipment: 'Pull-up bar', difficulty: 'intermediate', insight: 'A full dead-hang at the bottom counts more than a fast, half-range rep.', mode: 'strength', timer: null },
  { id: 'cal_chinup',             category: 'calisthenics', name: 'Chin-Up',                description: 'Underhand pull-up variation emphasizing biceps more heavily.', dosage: '3 x 5-10', equipment: 'Pull-up bar', difficulty: 'intermediate', insight: 'The underhand grip recruits more biceps — often the easier variant to start with.', mode: 'strength', timer: null },
  { id: 'cal_muscleup',           category: 'calisthenics', name: 'Muscle-Up',              description: 'Explosive transition from a pull-up into a dip — an advanced skill benchmark.', dosage: '3 x 2-5', equipment: 'Pull-up bar/rings', difficulty: 'advanced', insight: 'The transition itself — not the pull or dip alone — is usually the real limiter.', mode: 'strength', timer: null },
  { id: 'cal_australian_row',     category: 'calisthenics', name: 'Australian Row',         description: 'Bodyweight horizontal row done under a bar — a great pull-up-progression accessory.', dosage: '3 x 10-15', equipment: 'Bar/rings', difficulty: 'beginner', insight: 'Lower the bar for a harder angle once bodyweight reps feel too easy.', mode: 'strength', timer: null },
  { id: 'cal_pistol_squat',       category: 'calisthenics', name: 'Pistol Squat',           description: 'Single-leg bodyweight squat requiring strength, balance, and mobility.', dosage: '3 x 5-8 per leg', equipment: 'None', difficulty: 'advanced', insight: 'Ankle and hip mobility usually limits this before raw leg strength does.', mode: 'strength', timer: null },
  { id: 'cal_shrimp_squat',       category: 'calisthenics', name: 'Shrimp Squat',           description: 'Single-leg squat variation, an accessible stepping stone toward the pistol squat.', dosage: '3 x 6-10 per leg', equipment: 'None', difficulty: 'intermediate', insight: 'A great stepping stone that builds the same balance the pistol squat demands.', mode: 'strength', timer: null },
  { id: 'cal_bw_split_squat',     category: 'calisthenics', name: 'Bodyweight Bulgarian Split Squat', description: 'Rear-foot-elevated single-leg squat using bodyweight only.', dosage: '3 x 10-12 per leg', equipment: 'Bench/chair', difficulty: 'beginner', insight: 'Add a weighted vest or dumbbells once this feels too easy for reps.', mode: 'strength', timer: null },
  { id: 'cal_lsit',               category: 'calisthenics', name: 'L-Sit',                  description: 'Static core-and-hip-flexor hold with legs extended in front, parallel to the ground.', dosage: '3 x 10-20s', equipment: 'Parallettes/floor', difficulty: 'intermediate', insight: 'Push down through straight arms and point the toes — a strength hold, not a flexibility one.', mode: 'strength', timer: null },
  { id: 'cal_hollow_hold',        category: 'calisthenics', name: 'Hollow Body Hold',       description: 'Foundational core-tension position underlying most gymnastics-style calisthenics skills.', dosage: '3 x 20-30s', equipment: 'None', difficulty: 'beginner', insight: 'The lower back should stay pressed to the floor the entire time.', mode: 'strength', timer: null },
  { id: 'cal_plank_to_pushup',    category: 'calisthenics', name: 'Plank to Push-Up',       description: 'Alternating between forearm plank and push-up top position for core and shoulder stability.', dosage: '3 x 10-16 total', equipment: 'None', difficulty: 'beginner', insight: 'Move one arm at a time to keep the hips from rotating.', mode: 'strength', timer: null },
  { id: 'cal_archer_pushup',      category: 'calisthenics', name: 'Archer Push-Up',         description: 'Unilateral push-up variation shifting weight toward one arm — a one-arm push-up progression.', dosage: '3 x 5-8 per side', equipment: 'None', difficulty: 'advanced', insight: 'The straight arm should do almost no pushing — it\'s mostly there for balance.', mode: 'strength', timer: null },
  { id: 'cal_archer_pullup',      category: 'calisthenics', name: 'Archer Pull-Up',         description: 'Unilateral pull-up variation shifting weight to one arm — a one-arm pull-up progression.', dosage: '3 x 3-6 per side', equipment: 'Pull-up bar', difficulty: 'advanced', insight: 'Keep the straight arm\'s shoulder engaged, not just dangling passively.', mode: 'strength', timer: null },
  { id: 'cal_front_lever',        category: 'calisthenics', name: 'Front Lever Progression', description: 'Horizontal static hold hanging from a bar — a classic advanced strength benchmark.', dosage: '3 x 5-15s (tucked/adv. tucked)', equipment: 'Pull-up bar', difficulty: 'advanced', insight: 'A posterior pelvic tilt and hollow body make this dramatically easier to hold.', mode: 'strength', timer: null },
  { id: 'cal_back_lever',         category: 'calisthenics', name: 'Back Lever Progression', description: 'Horizontal static hold facing the ground, hanging from a bar.', dosage: '3 x 5-15s (tucked)', equipment: 'Pull-up bar/rings', difficulty: 'advanced', insight: 'Shoulder flexibility is often the real bottleneck here, not pulling strength.', mode: 'strength', timer: null },
  { id: 'cal_wall_handstand',     category: 'calisthenics', name: 'Handstand Hold (Wall)',  description: 'Inverted balance hold using the wall for support — the base of all handstand work.', dosage: '3 x 30-60s', equipment: 'Wall', difficulty: 'intermediate', insight: 'Face the wall, not away from it, for a version that trains real balance.', mode: 'strength', timer: null },
  { id: 'cal_freestanding_hs',    category: 'calisthenics', name: 'Freestanding Handstand Practice', description: 'Balance practice away from the wall, building toward a controlled freestanding handstand.', dosage: '10-15 min of short attempts', equipment: 'None', difficulty: 'advanced', insight: 'Short, frequent attempts beat occasional long sessions for building balance.', mode: 'strength', timer: null },
  { id: 'cal_nordic_curl',        category: 'calisthenics', name: 'Nordic Curl',            description: 'Eccentric hamstring-strength movement, anchored at the ankles, lowering under control.', dosage: '3 x 5-8', equipment: 'Partner/anchor', difficulty: 'advanced', insight: 'Lower as slowly as controllable — the eccentric portion is where the benefit lives.', mode: 'strength', timer: null },
  { id: 'cal_box_jump',           category: 'calisthenics', name: 'Box Jump',               description: 'Explosive bodyweight plyometric jump for power development.', dosage: '4 x 5', equipment: 'Box/platform', difficulty: 'intermediate', insight: "Step down, don't jump down — landing is where most box-jump injuries happen.", mode: 'strength', timer: null },
  { id: 'cal_burpee',             category: 'calisthenics', name: 'Burpee',                 description: 'Full-body conditioning movement combining a squat, plank, push-up, and jump.', dosage: '3 x 10-15', equipment: 'None', difficulty: 'beginner', insight: 'Keep the plank position brief and rigid instead of letting the hips sag.', mode: 'strength', timer: null },
  { id: 'cal_dragon_flag',        category: 'calisthenics', name: 'Dragon Flag',            description: 'Advanced core movement lowering the body from vertical while keeping it rigid.', dosage: '3 x 4-8', equipment: 'Bench', difficulty: 'advanced', insight: 'Only the shoulders touch the bench — everything else stays rigid and controlled.', mode: 'strength', timer: null },
  { id: 'cal_human_flag',         category: 'calisthenics', name: 'Human Flag Progression', description: 'Side-plank-style hold gripping a vertical pole with the body extended horizontally.', dosage: '3 x 3-10s attempts', equipment: 'Vertical pole', difficulty: 'advanced', insight: 'Build the tucked version first before attempting a fully extended flag.', mode: 'strength', timer: null },

  // ── Cycling ────────────────────────────────────────────────────────────
  { id: 'cyc_zone2_endurance',    category: 'cycling', name: 'Zone 2 Endurance Ride',       description: 'Long, easy-paced aerobic base ride.', dosage: '60-120 min', equipment: 'Bike', difficulty: 'beginner', insight: 'A cadence around 85-95rpm is a reasonable default if you\'re unsure.', mode: 'steady', timer: { durationSec: 5400 } },
  { id: 'cyc_sweet_spot',         category: 'cycling', name: 'Sweet Spot Intervals',         description: 'Sustained efforts just below threshold — high training benefit for moderate fatigue cost.', dosage: '2-3 x 15-20min @ 88-94% FTP', equipment: 'Bike, power meter/trainer', difficulty: 'intermediate', insight: 'The "sweet spot" name is literal — hard enough to matter, easy enough to recover from.', mode: 'interval', timer: { rounds: 3, workSec: 1050, restSec: 300 } },
  { id: 'cyc_vo2max',             category: 'cycling', name: 'VO2 Max Intervals (30/30s)', description: 'Very short, very hard efforts alternated with equal recovery to raise aerobic ceiling.', dosage: '2-3 sets of 10 x 30s on/30s off', equipment: 'Bike', difficulty: 'advanced', insight: 'Keep pedaling lightly during the "off" 30s — a full stop wastes the interval.', mode: 'interval', timer: { rounds: 20, workSec: 30, restSec: 30 } },
  { id: 'cyc_threshold',          category: 'cycling', name: 'Threshold Intervals',          description: 'Efforts at or near functional threshold power to raise sustainable race pace.', dosage: '2 x 20min @ FTP, 5min rest', equipment: 'Bike, power meter/trainer', difficulty: 'advanced', insight: 'Effort should sit right at the edge of sustainable — not a sprint, not comfortable.', mode: 'interval', timer: { rounds: 2, workSec: 1200, restSec: 300 } },
  { id: 'cyc_hill_climb',         category: 'cycling', name: 'Hill Climb Repeats',           description: 'Repeated seated/standing climbs for strength and threshold power.', dosage: '5-6 x 5min climb', equipment: 'Bike, hill', difficulty: 'intermediate', insight: 'Alternate seated and standing to spread the workload across different muscles.', mode: 'interval', timer: { rounds: 6, workSec: 300, restSec: 240 } },
  { id: 'cyc_cadence_drills',     category: 'cycling', name: 'Cadence Drills (High RPM)',    description: 'Spinning at high cadence with light resistance to improve pedaling efficiency.', dosage: '6 x 2min @ 100-110rpm', equipment: 'Bike', difficulty: 'beginner', insight: 'Keep the upper body relaxed — a high cadence should look smooth, not frantic.', mode: 'interval', timer: { rounds: 6, workSec: 120, restSec: 60 } },
  { id: 'cyc_recovery_spin',      category: 'cycling', name: 'Recovery Spin',                description: 'Very easy, low-resistance ride to promote recovery between hard sessions.', dosage: '30-45 min easy', equipment: 'Bike', difficulty: 'beginner', insight: 'Resistance should be low enough that pedaling feels almost too easy.', mode: 'steady', timer: { durationSec: 2250 } },
  { id: 'cyc_group_ride',         category: 'cycling', name: 'Group Ride / Group Pace',      description: 'Riding with others — variable intensity, drafting, and pack-riding skills.', dosage: '60-120 min', equipment: 'Bike', difficulty: 'intermediate', insight: 'Drafting saves real energy — hold a steady position rather than surging to catch up.', mode: 'steady', timer: { durationSec: 5400 } },
  { id: 'cyc_time_trial',         category: 'cycling', name: 'Time Trial Effort',            description: 'Sustained maximal solo effort over a set distance or duration.', dosage: '20-40 min max sustainable', equipment: 'Bike', difficulty: 'advanced', insight: 'Pacing evenly beats starting fast — a hard start rarely holds to the finish.', mode: 'steady', timer: { durationSec: 1800 } },
  { id: 'cyc_sprint_intervals',   category: 'cycling', name: 'Sprint Intervals (Standing Starts)', description: 'Maximal short sprints from a standing start for peak power.', dosage: '8-10 x 15s all-out, 3min rest', equipment: 'Bike', difficulty: 'advanced', insight: 'Full recovery matters more than squeezing in one more rep.', mode: 'interval', timer: { rounds: 9, workSec: 15, restSec: 180 } },
  { id: 'cyc_long_endurance',     category: 'cycling', name: 'Long Endurance Ride',          description: 'The weekly long ride — builds aerobic base and time-in-saddle tolerance.', dosage: '2-4 hours', equipment: 'Bike', difficulty: 'intermediate', insight: 'Practice on-bike nutrition here — it\'s as much a skill as the fitness itself.', mode: 'steady', timer: { durationSec: 10800 } },
  { id: 'cyc_ramp_test',          category: 'cycling', name: 'Indoor Trainer Ramp Test',     description: 'Progressively increasing-power test to estimate current FTP.', dosage: '~20 min total, ramping every min', equipment: 'Bike, smart trainer', difficulty: 'advanced', insight: 'Push until you truly can\'t hold the target power — stopping early underestimates FTP.', mode: 'steady', timer: { durationSec: 1200 } },
  { id: 'cyc_tempo_ride',         category: 'cycling', name: 'Tempo Ride',                   description: 'Moderately hard, sustainable effort below threshold.', dosage: '40-60 min @ 76-88% FTP', equipment: 'Bike', difficulty: 'intermediate', insight: 'Should feel like solid, sustainable work — not yet uncomfortable.', mode: 'steady', timer: { durationSec: 3000 } },
  { id: 'cyc_fartlek_ride',       category: 'cycling', name: 'Fartlek Ride',                 description: 'Unstructured surges of effort mixed into an otherwise easy ride.', dosage: '45-60 min with 6-8 surges', equipment: 'Bike', difficulty: 'beginner', insight: 'Use terrain — a hill, a straightaway — to naturally trigger each surge.', mode: 'steady', timer: { durationSec: 3150 } },
  { id: 'cyc_descending_skills',  category: 'cycling', name: 'Descending Skills Practice',   description: 'Deliberate practice of braking, line choice, and body position on descents.', dosage: '20-30 min', equipment: 'Bike, descent', difficulty: 'intermediate', insight: 'Look through the turn, not at the road right in front of the wheel.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'cyc_cornering_drills',   category: 'cycling', name: 'Cornering Drills',             description: 'Repeated practice of cornering technique at controlled speed.', dosage: '15-20 min', equipment: 'Bike', difficulty: 'intermediate', insight: 'Brake before the turn, not during it, for a smoother, faster line.', mode: 'steady', timer: { durationSec: 1050 } },
  { id: 'cyc_single_leg',         category: 'cycling', name: 'Single-Leg Pedaling Drill',    description: 'Pedaling with one leg at a time (other resting) to smooth the pedal stroke.', dosage: '6 x 1min per leg', equipment: 'Bike, trainer', difficulty: 'intermediate', insight: 'A choppy stroke usually means you\'re pushing down, not pulling through the full circle.', mode: 'interval', timer: { rounds: 12, workSec: 60, restSec: 10 } },
  { id: 'cyc_big_gear',           category: 'cycling', name: 'Big Gear Strength Intervals', description: 'Low-cadence, high-torque efforts for muscular strength on the bike.', dosage: '5 x 5min @ 50-60rpm', equipment: 'Bike', difficulty: 'advanced', insight: 'Stay seated with a strong core — this is strength work, not a sprint.', mode: 'interval', timer: { rounds: 5, workSec: 300, restSec: 180 } },
  { id: 'cyc_crit_sim',           category: 'cycling', name: 'Criterium Simulation',         description: 'Repeated hard accelerations mimicking the surges of criterium racing.', dosage: '45-60 min with 10-15 hard surges', equipment: 'Bike', difficulty: 'advanced', insight: 'The surges matter more than the steady pace between them — that\'s race-specific.', mode: 'steady', timer: { durationSec: 3150 } },
  { id: 'cyc_gravel_ride',        category: 'cycling', name: 'Gravel/Off-Road Ride',         description: 'Riding on unpaved surfaces — builds bike-handling skill alongside fitness.', dosage: '60-120 min', equipment: 'Gravel bike', difficulty: 'intermediate', insight: 'Slightly lower tire pressure improves both grip and comfort on rough surfaces.', mode: 'steady', timer: { durationSec: 5400 } },
  { id: 'cyc_brick_ride',         category: 'cycling', name: 'Brick Ride (Pre-Run)',         description: 'Bike ride immediately preceding a run, training the muscular transition for triathlon.', dosage: '45-60 min bike + short run', equipment: 'Bike', difficulty: 'intermediate', insight: 'The first few minutes off the bike will feel odd — that\'s exactly what you\'re training.', mode: 'steady', timer: { durationSec: 3150 } },
  { id: 'cyc_over_unders',        category: 'cycling', name: 'Over-Under Intervals',         description: 'Alternating just-above and just-below threshold power to simulate race surges.', dosage: '3 x 9min (3min over/under cycles)', equipment: 'Bike, power meter/trainer', difficulty: 'advanced', insight: 'The "under" segment is active recovery, not full rest — keep pushing power.', mode: 'interval', timer: { rounds: 3, workSec: 540, restSec: 180 } },
  { id: 'cyc_post_race_recovery', category: 'cycling', name: 'Recovery Ride (Post-Race)',    description: 'Very light spin the day after a race or hard event to aid recovery.', dosage: '30-40 min very easy', equipment: 'Bike', difficulty: 'beginner', insight: 'True recovery rides should feel optional, not forced — skip it if unsure it\'s needed.', mode: 'steady', timer: { durationSec: 2100 } },
  { id: 'cyc_seated_climb',       category: 'cycling', name: 'Hill Repeat Seated Climb',     description: 'Climbing repeats staying seated throughout to isolate seated-climbing strength.', dosage: '5 x 4min seated climb', equipment: 'Bike, hill', difficulty: 'intermediate', insight: 'Staying seated forces the glutes and hamstrings to do more of the work.', mode: 'interval', timer: { rounds: 5, workSec: 240, restSec: 180 } },
  { id: 'cyc_aero_position',      category: 'cycling', name: 'Aero Position Practice Ride',  description: 'Time spent riding in an aero/TT position to build comfort and sustainable power there.', dosage: '30-45 min in aero bars', equipment: 'Bike, aero bars', difficulty: 'intermediate', insight: 'Comfort in the aero position takes repeated practice — it rarely feels natural at first.', mode: 'steady', timer: { durationSec: 2250 } },

  // ── Swimming ───────────────────────────────────────────────────────────
  { id: 'swim_catchup_drill',     category: 'swimming', name: 'Freestyle Catch-Up Drill',   description: 'Technique drill pausing one arm at full extension until the other catches up, reinforcing long stroke timing.', dosage: '6 x 50m', equipment: 'Pool', difficulty: 'beginner', insight: 'Forces a full extension and longer stroke you can carry into normal swimming.', mode: 'interval', timer: { rounds: 6, workSec: 45, restSec: 20 } },
  { id: 'swim_endurance_set',     category: 'swimming', name: 'Freestyle Endurance Set',     description: 'Continuous freestyle swimming to build aerobic base in the water.', dosage: '1000-2000m continuous', equipment: 'Pool', difficulty: 'intermediate', insight: 'Focus on a consistent stroke count per length as fatigue sets in.', mode: 'steady', timer: { durationSec: 1800 } },
  { id: 'swim_kick_set',          category: 'swimming', name: 'Kick Set (Board, Flutter Kick)', description: 'Isolated kicking using a board to build leg drive and ankle flexibility.', dosage: '8 x 50m', equipment: 'Pool, kickboard', difficulty: 'beginner', insight: 'Kick from the hips, not just the knees, for real propulsion.', mode: 'interval', timer: { rounds: 8, workSec: 50, restSec: 20 } },
  { id: 'swim_pull_set',          category: 'swimming', name: 'Pull Set (Buoy, Pull Focus)', description: 'Upper-body-only swimming using a pull buoy to isolate the arm pull.', dosage: '6 x 100m', equipment: 'Pool, pull buoy', difficulty: 'intermediate', insight: 'Isolates arm strength by removing the legs from the equation entirely.', mode: 'interval', timer: { rounds: 6, workSec: 100, restSec: 30 } },
  { id: 'swim_100_intervals',     category: 'swimming', name: '100s Interval Set',          description: 'Repeated 100m efforts on a set send-off interval for pacing consistency.', dosage: '10 x 100m on 2:00', equipment: 'Pool, pace clock', difficulty: 'intermediate', insight: 'A consistent split every rep matters more than one fast, uneven one.', mode: 'interval', timer: { rounds: 10, workSec: 90, restSec: 30 } },
  { id: 'swim_50_sprint',         category: 'swimming', name: '50s Sprint Set',             description: 'Short maximal-effort sprints with generous rest for pure speed.', dosage: '8 x 50m all-out, 1min rest', equipment: 'Pool', difficulty: 'advanced', insight: 'Full recovery between reps — this is about top-end speed, not endurance.', mode: 'interval', timer: { rounds: 8, workSec: 35, restSec: 60 } },
  { id: 'swim_im_set',            category: 'swimming', name: 'Individual Medley (IM) Set', description: 'Rotating through all four competitive strokes for well-rounded technique work.', dosage: '4 x 100m IM', equipment: 'Pool', difficulty: 'advanced', insight: 'The transition between strokes often costs more time than the strokes themselves.', mode: 'interval', timer: { rounds: 4, workSec: 100, restSec: 30 } },
  { id: 'swim_breaststroke_drill', category: 'swimming', name: 'Breaststroke Technique Drill', description: 'Isolated drilling of the breaststroke kick and pull timing.', dosage: '6 x 50m', equipment: 'Pool', difficulty: 'beginner', insight: 'Timing between the kick and pull matters more than raw power here.', mode: 'interval', timer: { rounds: 6, workSec: 50, restSec: 20 } },
  { id: 'swim_backstroke_drill',  category: 'swimming', name: 'Backstroke Technique Drill', description: 'Isolated drilling of backstroke body rotation and arm recovery.', dosage: '6 x 50m', equipment: 'Pool', difficulty: 'beginner', insight: 'Body rotation drives the stroke more than the arms alone.', mode: 'interval', timer: { rounds: 6, workSec: 50, restSec: 20 } },
  { id: 'swim_butterfly_drill',   category: 'swimming', name: 'Butterfly Drill (Single-Arm)', description: 'Single-arm butterfly to reduce fatigue while still building the undulation pattern.', dosage: '6 x 25m per arm', equipment: 'Pool', difficulty: 'advanced', insight: 'Removes the two-arm timing challenge so you can focus purely on the undulation.', mode: 'interval', timer: { rounds: 6, workSec: 25, restSec: 20 } },
  { id: 'swim_sighting_practice', category: 'swimming', name: 'Open Water Sighting Practice', description: 'Practicing periodic head-lifts to sight a target, essential for open-water racing.', dosage: '8 x 50m with sighting every 6 strokes', equipment: 'Pool/open water', difficulty: 'intermediate', insight: 'Sight quickly, then return your face to the water — don\'t swim with your head up.', mode: 'interval', timer: { rounds: 8, workSec: 50, restSec: 20 } },
  { id: 'swim_descending_set',    category: 'swimming', name: 'Descending Set',             description: 'Repeats that get progressively faster each rep.', dosage: '5 x 100m descend 1-5', equipment: 'Pool', difficulty: 'intermediate', insight: 'Start conservatively — the whole point is having something left to descend into.', mode: 'interval', timer: { rounds: 5, workSec: 100, restSec: 20 } },
  { id: 'swim_negative_split_400', category: 'swimming', name: 'Negative Split 400',         description: 'A single 400m swum with the second 200m faster than the first.', dosage: '1-3 x 400m negative split', equipment: 'Pool', difficulty: 'intermediate', insight: 'An honest, conservative first 200 pace is the hardest part to commit to.', mode: 'interval', timer: { rounds: 2, workSec: 360, restSec: 120 } },
  { id: 'swim_sculling_drill',    category: 'swimming', name: 'Sculling Drill',             description: 'Small hand movements to build feel for the water and catch technique.', dosage: '4 x 25m', equipment: 'Pool', difficulty: 'beginner', insight: 'Use just the forearms and hands — this builds feel for the water, not power.', mode: 'interval', timer: { rounds: 4, workSec: 40, restSec: 20 } },
  { id: 'swim_bilateral_breathing', category: 'swimming', name: 'Bilateral Breathing Drill', description: 'Alternating breathing sides every 3 strokes to build symmetrical stroke mechanics.', dosage: '8 x 50m', equipment: 'Pool', difficulty: 'beginner', insight: 'Uncomfortable at first on the "weak" side — that\'s exactly the point.', mode: 'interval', timer: { rounds: 8, workSec: 50, restSec: 20 } },
  { id: 'swim_fins_kick_set',     category: 'swimming', name: 'Fins Kick Set',              description: 'Kicking with fins to build ankle flexibility and propulsion power.', dosage: '6 x 50m', equipment: 'Pool, fins', difficulty: 'beginner', insight: 'Fins amplify kick technique flaws as much as they add propulsion — watch your form.', mode: 'interval', timer: { rounds: 6, workSec: 45, restSec: 20 } },
  { id: 'swim_paddle_strength',   category: 'swimming', name: 'Paddle Strength Set',        description: 'Swimming with hand paddles to overload the pull for strength gains.', dosage: '6 x 100m', equipment: 'Pool, paddles', difficulty: 'advanced', insight: 'Start with smaller paddles — oversized ones increase shoulder strain.', mode: 'interval', timer: { rounds: 6, workSec: 90, restSec: 30 } },
  { id: 'swim_tempo_trainer',     category: 'swimming', name: 'Tempo Trainer Pace Work',     description: 'Swimming to an audible beep device to lock in a target stroke rate.', dosage: '8 x 100m at set tempo', equipment: 'Pool, tempo trainer', difficulty: 'advanced', insight: 'Match the beep exactly rather than swimming your natural rhythm.', mode: 'interval', timer: { rounds: 8, workSec: 90, restSec: 20 } },
  { id: 'swim_broken_1500',       category: 'swimming', name: 'Broken 1500 (Race Pace)',     description: 'A 1500m broken into shorter reps at race pace with brief rest, easier on pacing than a straight swim.', dosage: '15 x 100m @ race pace, 10s rest', equipment: 'Pool', difficulty: 'advanced', insight: 'The short rest keeps aerobic stress high while still allowing race-pace practice.', mode: 'interval', timer: { rounds: 15, workSec: 90, restSec: 10 } },
  { id: 'swim_recovery',          category: 'swimming', name: 'Recovery Swim',              description: 'Easy continuous swimming, any stroke, to aid recovery.', dosage: '20-30 min easy', equipment: 'Pool', difficulty: 'beginner', insight: 'Any stroke, easy effort — the goal is blood flow, not training stimulus.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'swim_ladder_set',        category: 'swimming', name: 'Ladder Set',                 description: 'Progressively longer then shorter reps (100-200-300-200-100) for varied pacing practice.', dosage: '100-200-300-200-100m', equipment: 'Pool', difficulty: 'intermediate', insight: 'Pace the longest middle swim conservatively — it sets up the whole set.', mode: 'steady', timer: { durationSec: 1200 } },
  { id: 'swim_dive_start',        category: 'swimming', name: 'Dive/Start Practice',         description: 'Repeated practice of racing starts for competitive efficiency.', dosage: '6-8 starts', equipment: 'Pool, starting block', difficulty: 'intermediate', insight: 'A clean entry with minimal splash carries real speed into the first strokes.', mode: 'interval', timer: { rounds: 7, workSec: 15, restSec: 45 } },
  { id: 'swim_turn_practice',     category: 'swimming', name: 'Turn/Flip Turn Practice',     description: 'Repeated wall-turn practice to minimize time lost at each length.', dosage: '10-12 turns', equipment: 'Pool', difficulty: 'intermediate', insight: 'A fast turn can save more time per length than swimming faster.', mode: 'interval', timer: { rounds: 11, workSec: 15, restSec: 20 } },
  { id: 'swim_css_threshold',     category: 'swimming', name: 'Threshold Swim Set (CSS Pace)', description: 'Efforts at Critical Swim Speed, the swimming analog to lactate threshold.', dosage: '6 x 200m @ CSS pace', equipment: 'Pool, pace clock', difficulty: 'advanced', insight: 'This pace should feel "controlled hard" — sustainable for the whole set, not comfortable.', mode: 'interval', timer: { rounds: 6, workSec: 180, restSec: 30 } },
  { id: 'swim_cooldown',          category: 'swimming', name: 'Cool-Down Swim',              description: 'Very easy swimming to close out a session and flush the arms/legs.', dosage: '5-10 min easy', equipment: 'Pool', difficulty: 'beginner', insight: 'Very easy, any stroke — the goal is flushing out, not more training.', mode: 'steady', timer: { durationSec: 450 } },

  // ── Boxing ─────────────────────────────────────────────────────────────
  { id: 'box_shadowboxing',       category: 'boxing', name: 'Shadowboxing (Technique Focus)', description: 'Unloaded practice of stance, footwork, and combinations in front of a mirror.', dosage: '3-5 x 3min rounds', equipment: 'None', difficulty: 'beginner', insight: 'Watching yourself in the mirror catches technique flaws you can\'t feel.', mode: 'interval', timer: { rounds: 4, workSec: 180, restSec: 60 } },
  { id: 'box_heavy_bag_combos',   category: 'boxing', name: 'Heavy Bag Combinations',        description: 'Loaded combination punching for power and conditioning.', dosage: '6 x 3min rounds, 1min rest', equipment: 'Heavy bag, gloves', difficulty: 'intermediate', insight: 'Reset your hands to guard after every combination, not just some.', mode: 'interval', timer: { rounds: 6, workSec: 180, restSec: 60 } },
  { id: 'box_focus_mitts',        category: 'boxing', name: 'Focus Mitts (Pad Work)',        description: 'Partner-held pad work for combination accuracy, timing, and reaction.', dosage: '4-6 x 3min rounds', equipment: 'Focus mitts, partner', difficulty: 'intermediate', insight: 'A pad holder calling unpredictable combinations is what builds real reaction speed.', mode: 'interval', timer: { rounds: 5, workSec: 180, restSec: 60 } },
  { id: 'box_jab_cross',          category: 'boxing', name: 'Jab-Cross Drill',               description: 'Repetition of the fundamental two-punch combination for form and speed.', dosage: '5 x 2min', equipment: 'None/bag', difficulty: 'beginner', insight: 'Snap the jab back quickly — it\'s a probe and a guard, not a committed punch.', mode: 'interval', timer: { rounds: 5, workSec: 120, restSec: 45 } },
  { id: 'box_slip_counter',       category: 'boxing', name: 'Slip and Counter Drill',        description: 'Defensive head movement paired with an immediate counter-punch.', dosage: '4 x 3min rounds', equipment: 'Partner/bag', difficulty: 'intermediate', insight: 'Slip with the whole upper body, not just a small head tilt.', mode: 'interval', timer: { rounds: 4, workSec: 180, restSec: 60 } },
  { id: 'box_footwork_ladder',    category: 'boxing', name: 'Footwork Ladder Drill',         description: 'Agility ladder drills adapted for boxing stance and lateral movement.', dosage: '6 x 30s', equipment: 'Agility ladder', difficulty: 'beginner', insight: 'Stay on the balls of the feet — flat-footed drilling rarely translates to the ring.', mode: 'interval', timer: { rounds: 6, workSec: 30, restSec: 30 } },
  { id: 'box_speed_bag',          category: 'boxing', name: 'Speed Bag Work',                description: 'Rhythm and hand-speed development on the speed bag.', dosage: '5 x 3min rounds', equipment: 'Speed bag', difficulty: 'intermediate', insight: 'Rhythm and consistency matter far more than raw speed at first.', mode: 'interval', timer: { rounds: 5, workSec: 180, restSec: 60 } },
  { id: 'box_double_end_bag',     category: 'boxing', name: 'Double-End Bag Work',           description: 'Reactive punching against an unpredictable rebounding bag for timing and accuracy.', dosage: '4 x 2min rounds', equipment: 'Double-end bag', difficulty: 'advanced', insight: 'The unpredictable rebound is the whole point — don\'t anticipate, react.', mode: 'interval', timer: { rounds: 4, workSec: 120, restSec: 60 } },
  { id: 'box_defensive_rolling',  category: 'boxing', name: 'Defensive Rolling Drill',       description: 'Continuous upper-body rolling under simulated punches to build defensive reflexes.', dosage: '4 x 2min', equipment: 'Partner/bag', difficulty: 'intermediate', insight: 'Roll under the punch\'s path, not just backward away from it.', mode: 'interval', timer: { rounds: 4, workSec: 120, restSec: 45 } },
  { id: 'box_body_shots',         category: 'boxing', name: 'Body Shot Combinations',        description: 'Combinations targeting the body, requiring bent-knee positioning and core rotation.', dosage: '5 x 3min rounds', equipment: 'Heavy bag', difficulty: 'intermediate', insight: 'Bend the knees to get low on body shots — don\'t just drop the arm.', mode: 'interval', timer: { rounds: 5, workSec: 180, restSec: 60 } },
  { id: 'box_uppercut_drill',     category: 'boxing', name: 'Uppercut Drill',                description: 'Repetition drilling of the uppercut for close-range power punching.', dosage: '4 x 2min', equipment: 'Bag/mitts', difficulty: 'intermediate', insight: 'Power comes from the legs and hips rotating, not the arm alone.', mode: 'interval', timer: { rounds: 4, workSec: 120, restSec: 45 } },
  { id: 'box_hook_combo',         category: 'boxing', name: 'Hook Combination Drill',        description: 'Combination drilling built around the lead and rear hook.', dosage: '4 x 2min', equipment: 'Bag/mitts', difficulty: 'intermediate', insight: 'Pivot the back foot — a hook thrown flat-footed loses most of its power.', mode: 'interval', timer: { rounds: 4, workSec: 120, restSec: 45 } },
  { id: 'box_sparring',           category: 'boxing', name: 'Sparring (Controlled)',         description: 'Live, controlled-intensity practice against a partner — the closest simulation to competition.', dosage: '3-4 x 3min rounds', equipment: 'Gloves, headgear, partner', difficulty: 'advanced', insight: 'Controlled means working technique, not proving toughness — ego is the biggest risk here.', mode: 'interval', timer: { rounds: 4, workSec: 180, restSec: 60 } },
  { id: 'box_rope_jumping',       category: 'boxing', name: 'Rope Jumping (Conditioning)',   description: 'Classic boxing conditioning tool for footwork rhythm and cardio.', dosage: '5 x 3min rounds', equipment: 'Jump rope', difficulty: 'beginner', insight: 'Stay light on the feet with small hops — jumping high just wastes energy.', mode: 'interval', timer: { rounds: 5, workSec: 180, restSec: 60 } },
  { id: 'box_interval_bag_rounds', category: 'boxing', name: 'Interval Bag Rounds',           description: 'Standard 3-minutes-on/1-minute-off bag rounds mimicking amateur bout structure.', dosage: '6 x (3min on / 1min off)', equipment: 'Heavy bag', difficulty: 'intermediate', insight: 'The rest minute matters as much as the work — don\'t skip it to "push through."', mode: 'interval', timer: { rounds: 6, workSec: 180, restSec: 60 } },
  { id: 'box_reaction_ball',      category: 'boxing', name: 'Reaction Ball Drill',           description: 'Catching/reacting to an unpredictably bouncing ball to sharpen reflexes.', dosage: '3 x 3min', equipment: 'Reaction ball', difficulty: 'beginner', insight: 'Keep eyes on the ball, not on where you expect it to bounce.', mode: 'interval', timer: { rounds: 3, workSec: 180, restSec: 45 } },
  { id: 'box_counter_punching',   category: 'boxing', name: 'Counter-Punching Drill',        description: 'Drilling immediate counter-attacks off a partner\'s or coach\'s lead punches.', dosage: '4 x 3min rounds', equipment: 'Partner/mitts', difficulty: 'advanced', insight: 'Counters land in the gap right after an opponent\'s punch, not before it.', mode: 'interval', timer: { rounds: 4, workSec: 180, restSec: 60 } },
  { id: 'box_clinch_work',        category: 'boxing', name: 'Clinch Work',                   description: 'Close-range control and disengagement practice.', dosage: '3 x 2min', equipment: 'Partner', difficulty: 'intermediate', insight: 'Underhooks and head position usually decide control more than raw strength.', mode: 'interval', timer: { rounds: 3, workSec: 120, restSec: 45 } },
  { id: 'box_southpaw_switch',    category: 'boxing', name: 'Southpaw Switch Drill',         description: 'Practicing combinations from the opposite stance to develop switch-hitting ability.', dosage: '4 x 2min', equipment: 'Bag', difficulty: 'advanced', insight: 'Expect it to feel clumsy at first — that\'s normal, not a sign you\'re doing it wrong.', mode: 'interval', timer: { rounds: 4, workSec: 120, restSec: 45 } },
  { id: 'box_power_development',  category: 'boxing', name: 'Power Punch Development',       description: 'Full-power single punches with complete recovery, focused purely on force output.', dosage: '5 x 5 max-power punches', equipment: 'Heavy bag', difficulty: 'advanced', insight: 'Full recovery between punches — this trains force output, not conditioning.', mode: 'interval', timer: { rounds: 5, workSec: 15, restSec: 90 } },
  { id: 'box_combo_numbering',    category: 'boxing', name: 'Combination Number System Drill', description: 'Calling out numbered combinations (1=jab, 2=cross, etc.) for rapid-response training.', dosage: '5 x 2min', equipment: 'Partner/coach, bag', difficulty: 'intermediate', insight: 'Fast, accurate calling builds reaction speed more than the punches themselves.', mode: 'interval', timer: { rounds: 5, workSec: 120, restSec: 45 } },
  { id: 'box_cardio_circuit',     category: 'boxing', name: 'Cardio Boxing Circuit',         description: 'Circuit blending punching combinations with bodyweight conditioning exercises.', dosage: '20-30 min circuit', equipment: 'Bag, mat', difficulty: 'beginner', insight: 'Punching form usually breaks down first as fatigue sets in — watch for it.', mode: 'steady', timer: { durationSec: 1500 } },
  { id: 'box_wall_ball_reflex',   category: 'boxing', name: 'Wall Ball Reflex Drill',        description: 'Rapid-fire reaction drill catching/punching a ball rebounding off a wall.', dosage: '4 x 2min', equipment: 'Reflex ball, wall', difficulty: 'intermediate', insight: 'Unpredictable rebounds off the wall sharpen reaction time better than a fixed pattern.', mode: 'interval', timer: { rounds: 4, workSec: 120, restSec: 45 } },
  { id: 'box_distance_management', category: 'boxing', name: 'Distance Management Drill',    description: 'Footwork-focused practice controlling range in and out of punching distance.', dosage: '4 x 3min rounds', equipment: 'Partner', difficulty: 'advanced', insight: 'Small steps in and out control range better than big lunging movements.', mode: 'interval', timer: { rounds: 4, workSec: 180, restSec: 60 } },
  { id: 'box_cooldown_shadowbox', category: 'boxing', name: 'Cool-Down Shadowboxing',        description: 'Very light shadowboxing to close a session and bring heart rate down gradually.', dosage: '3-5 min', equipment: 'None', difficulty: 'beginner', insight: 'Very light effort — the goal is bringing heart rate down, not more training.', mode: 'steady', timer: { durationSec: 240 } },

  // ── Stretching / Mobility ──────────────────────────────────────────────
  { id: 'stretch_standing_hamstring', category: 'stretch', name: 'Standing Hamstring Stretch', description: 'Basic static stretch targeting the back of the thigh.', dosage: 'Hold 30s x2 per leg', equipment: 'None', difficulty: 'beginner', insight: 'A slight bend in the knee often allows a deeper, safer stretch.', mode: 'mobility', timer: null },
  { id: 'stretch_couch',          category: 'stretch', name: 'Couch Stretch (Hip Flexor)',   description: 'Deep hip-flexor stretch using a wall or couch to anchor the rear leg.', dosage: 'Hold 60-90s per side', equipment: 'Wall/couch', difficulty: 'intermediate', insight: 'Squeeze the glute on the stretched side to deepen the hip-flexor release.', mode: 'mobility', timer: null },
  { id: 'stretch_pigeon',         category: 'stretch', name: 'Pigeon Pose',                  description: 'Deep external hip-rotator and glute stretch.', dosage: 'Hold 45-60s per side', equipment: 'Mat', difficulty: 'intermediate', insight: 'Keep hips square — letting them rotate open reduces the actual stretch.', mode: 'mobility', timer: null },
  { id: 'stretch_worlds_greatest', category: 'stretch', name: "World's Greatest Stretch",     description: 'Multi-plane dynamic stretch flowing through hip, hamstring, and thoracic mobility in one movement.', dosage: '5-8 reps per side', equipment: 'None', difficulty: 'beginner', insight: 'Move slowly through each position — rushing skips most of the benefit.', mode: 'mobility', timer: null },
  { id: 'stretch_cat_cow',        category: 'stretch', name: 'Cat-Cow Mobility Flow',        description: 'Alternating spinal flexion/extension flow for spine mobility.', dosage: '10-12 reps', equipment: 'Mat', difficulty: 'beginner', insight: 'Lead with the breath — inhale into cow, exhale into cat.', mode: 'mobility', timer: null },
  { id: 'stretch_thoracic_rotation', category: 'stretch', name: 'Thoracic Spine Rotation',    description: 'Quadruped rotational drill improving upper-back mobility.', dosage: '8-10 reps per side', equipment: 'Mat', difficulty: 'beginner', insight: 'Keep the hips still so the rotation actually comes from the upper back.', mode: 'mobility', timer: null },
  { id: 'stretch_shoulder_dislocates', category: 'stretch', name: 'Shoulder Dislocates',       description: 'Overhead band/stick pass-through improving shoulder range of motion.', dosage: '10-15 reps', equipment: 'Band/stick', difficulty: 'beginner', insight: 'Start with a wide grip and narrow it gradually as shoulders open up.', mode: 'mobility', timer: null },
  { id: 'stretch_90_90_hip',      category: 'stretch', name: '90/90 Hip Stretch',            description: 'Seated hip-mobility drill working internal and external rotation of both hips.', dosage: '5 reps per side, hold 10s', equipment: 'Mat', difficulty: 'intermediate', insight: 'Keep the spine tall — slouching lets the hips cheat the stretch.', mode: 'mobility', timer: null },
  { id: 'stretch_calf_wall',      category: 'stretch', name: 'Calf Stretch (Wall)',          description: 'Standing calf stretch against a wall, targeting the gastrocnemius.', dosage: 'Hold 30s x2 per leg', equipment: 'Wall', difficulty: 'beginner', insight: 'Keep the back heel flat on the ground for the stretch to actually work.', mode: 'mobility', timer: null },
  { id: 'stretch_quad_standing',  category: 'stretch', name: 'Quad Stretch (Standing)',       description: 'Standing stretch for the front of the thigh, holding the ankle behind the body.', dosage: 'Hold 30s x2 per leg', equipment: 'None', difficulty: 'beginner', insight: 'Tuck the pelvis slightly under to feel this more in the quad, less in the knee.', mode: 'mobility', timer: null },
  { id: 'stretch_seated_forward_fold', category: 'stretch', name: 'Seated Forward Fold',       description: 'Seated hamstring and lower-back stretch reaching toward the toes.', dosage: 'Hold 45-60s', equipment: 'Mat', difficulty: 'beginner', insight: 'Hinge from the hips, not the lower back, to protect the spine.', mode: 'mobility', timer: null },
  { id: 'stretch_butterfly',      category: 'stretch', name: 'Butterfly Stretch (Groin)',    description: 'Seated stretch for the inner thigh/adductors with soles of feet together.', dosage: 'Hold 45-60s', equipment: 'Mat', difficulty: 'beginner', insight: 'Let gravity do the work — forcefully pressing the knees down rarely helps.', mode: 'mobility', timer: null },
  { id: 'stretch_childs_pose',    category: 'stretch', name: "Child's Pose",                 description: 'Resting stretch for the lower back, hips, and shoulders.', dosage: 'Hold 45-60s', equipment: 'Mat', difficulty: 'beginner', insight: 'Widen the knees if reaching the arms forward feels restricted.', mode: 'mobility', timer: null },
  { id: 'stretch_downward_dog',   category: 'stretch', name: 'Downward Dog',                 description: 'Full posterior-chain stretch from calves to shoulders in an inverted V shape.', dosage: 'Hold 30-45s', equipment: 'Mat', difficulty: 'beginner', insight: 'A soft bend in the knees is fine if hamstrings are tight — don\'t force straight legs.', mode: 'mobility', timer: null },
  { id: 'stretch_cobra',          category: 'stretch', name: 'Cobra Stretch',                description: 'Gentle backbend stretching the abdominals and hip flexors.', dosage: 'Hold 20-30s x2', equipment: 'Mat', difficulty: 'beginner', insight: 'Keep the hips on the ground — lifting them turns this into a different stretch.', mode: 'mobility', timer: null },
  { id: 'stretch_ankle_mobility', category: 'stretch', name: 'Ankle Mobility Drill',         description: 'Weight-bearing ankle rocks improving dorsiflexion range of motion.', dosage: '10-12 reps per side', equipment: 'Wall', difficulty: 'beginner', insight: 'Keep the heel planted — the knee should travel forward over the toes.', mode: 'mobility', timer: null },
  { id: 'stretch_wrist_mobility', category: 'stretch', name: 'Wrist Mobility Flow',          description: 'Circular and flexion/extension wrist movements — important for handstand/pressing work.', dosage: '2-3 min', equipment: 'None', difficulty: 'beginner', insight: 'Especially useful as prep before any handstand or heavy pressing work.', mode: 'mobility', timer: null },
  { id: 'stretch_neck_mobility', category: 'stretch', name: 'Neck Mobility Circles',        description: 'Gentle neck circles and tilts to release tension.', dosage: '5 reps each direction', equipment: 'None', difficulty: 'beginner', insight: 'Keep movements slow and pain-free — this is mobility, not a stretch to force.', mode: 'mobility', timer: null },
  { id: 'stretch_it_band',        category: 'stretch', name: 'Standing IT Band Stretch',     description: 'Standing crossover stretch targeting the iliotibial band along the outer thigh.', dosage: 'Hold 30s x2 per side', equipment: 'None', difficulty: 'beginner', insight: 'The IT band often responds better to foam rolling than static stretching alone.', mode: 'mobility', timer: null },
  { id: 'stretch_deep_squat_hold', category: 'stretch', name: 'Deep Squat Hold',              description: 'Resting in a full-depth squat to build ankle, hip, and lower-back mobility.', dosage: 'Hold 60-90s', equipment: 'None', difficulty: 'intermediate', insight: 'Heels stay flat — rising onto the toes means ankle mobility is the real limiter.', mode: 'mobility', timer: null },
  { id: 'stretch_spiderman',      category: 'stretch', name: 'Spiderman Stretch with Rotation', description: 'Deep lunge with a reaching trunk rotation for hips and thoracic spine together.', dosage: '6-8 reps per side', equipment: 'None', difficulty: 'intermediate', insight: 'Reach the rotating arm toward the ceiling for the full thoracic benefit.', mode: 'mobility', timer: null },
  { id: 'stretch_foam_roll_quads', category: 'stretch', name: 'Foam Rolling - Quads/IT Band', description: 'Self-myofascial release for the front and side of the thigh.', dosage: '60-90s per side', equipment: 'Foam roller', difficulty: 'beginner', insight: 'Slow, controlled passes work better than fast rolling back and forth.', mode: 'mobility', timer: null },
  { id: 'stretch_foam_roll_upper_back', category: 'stretch', name: 'Foam Rolling - Upper Back', description: 'Self-myofascial release across the thoracic spine and lats.', dosage: '60-90s', equipment: 'Foam roller', difficulty: 'beginner', insight: 'Support the head with your hands to protect the neck while rolling.', mode: 'mobility', timer: null },
  { id: 'stretch_doorway_chest',  category: 'stretch', name: 'Doorway Chest Stretch',        description: 'Chest and anterior shoulder stretch using a doorframe for leverage.', dosage: 'Hold 30s x2 per side', equipment: 'Doorway', difficulty: 'beginner', insight: 'Adjust arm height on the doorframe to shift the stretch across different fibers.', mode: 'mobility', timer: null },
  { id: 'stretch_full_body_cooldown', category: 'stretch', name: 'Full Body Cool-Down Flow', description: 'A short sequence moving through the major muscle groups to close out any session.', dosage: '5-8 min flow', equipment: 'Mat', difficulty: 'beginner', insight: 'No need to hold any position long — the goal is a gentle transition out of training.', mode: 'mobility', timer: null }
];

function exercisesByCategory(category) {
  return EXERCISE_TEMPLATES.filter(e => e.category === category);
}

function findExercise(id) {
  return EXERCISE_TEMPLATES.find(e => e.id === id) || null;
}

module.exports = { EXERCISE_TEMPLATES, exercisesByCategory, findExercise };
